version: '3'

services:
  postgres:
    restart: always
    expose:
      - "5433"
    ports:
      - "5433:5433"
    command: -p 5433
    build: ./postgres
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: password1234
        POSTGRES_DB: TZ
    
  adminer:
    restart: always
    image: adminer
    ports:
      - 8888:8080
    depends_on:
      - postgres

volumes:
  postgres_data: